#!/usr/bin/perl
#
#
#   score_scale.pl
#
#   - calculate the Spearman correlation between two sets of rated word pairs
#
#   - see http://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient
#
#
#
#   Peter Turney
#   April 3, 2012
#
#
#
#
#   load package for calculating Spearman's rho
#
#   - see http://search.cpan.org/~gene/Statistics-RankCorrelation-0.1203/
#
use Statistics::RankCorrelation;
#
#
#
#
#
#   check command line arguments
#
if ($#ARGV != 2) {
  print "\n\nUsage:\n\n";
  print "score_scale.pl <input file of Gold Standard pair ratings> <input file of pair ratings to be evaluated> <output file of results>\n\n";
  exit;
}
#
#
#   input file of Gold Standard pair ratings
#
$gold_file = $ARGV[0];
#
#   input file of pair ratings to be evaluated
#
$test_file = $ARGV[1];
#
#   output file of results
#
$out_file = $ARGV[2];
#
#
#
#
#
#
#
#   read in the Gold file
#
print "reading the Gold Standard file $gold_file ...\n";
#
%pair2gold = ();
$num_gold  = 0;
#
open(INF, "< $gold_file");
#
while ($line = <INF>) {
  if ($line =~ /^\#/) { next; }         # skip comments
  if ($line =~ /(\S+)\s+(\S+)/) {
    $scale = $1;
    $pair  = $2;
    $pair2gold{$pair} = $scale;
    $num_gold++;
  }
}
#
close(INF);
#
print "... read $num_gold pairs ...\n";
print "... done.\n";
#
#
#
#
#
#   read in the test pair
#
print "reading the test file $test_file ...\n";
#
%pair2test = ();
$num_test  = 0;
#
open(INF, "< $test_file");
#
while ($line = <INF>) {
  if ($line =~ /^\#/) { next; }         # skip comments
  if ($line =~ /(\S+)\s+(\S+)/) {
    $scale = $1;
    $pair  = $2;
    $pair2test{$pair} = $scale;
    $num_test++;
  }
}
#
close(INF);
#
print "... read $num_test pairs ...\n";
print "... done.\n";
#
if ($num_test != $num_gold) {
  die "ERROR: $gold_file has $num_gold pairs but $test_file has $num_test pairs\n";
}
#
#
#
#
#
#
#
#   write out the results
#
print "writing results to $out_file ...\n";
#
@pairs = keys %pair2gold;
@gold  = ();
@test  = ();
#
foreach $pair (@pairs) {
  $gold_scale = $pair2gold{$pair};
  $test_scale = $pair2test{$pair};
  if (! defined($test_scale)) {
    die "ERROR: $pair was not found in $test_file\n";
  }
  push(@gold, $gold_scale);
  push(@test, $test_scale);
}
#
$cor = Statistics::RankCorrelation->new(\@gold, \@test);
$rho = $cor->spearman;
#
#   if all of the value in @test are the same, set the correlation to zero
#
$same  = 1;
$first = $test[0];
foreach $val (@test) {
  if ($val != $first) { 
    $same = 0;
    last;
  }
}
if ($same == 1) {
  $rho = 0;
  print "... all values in $test_file are the same ...\n";
}
#
print "... correlation is $rho ...\n";
#
open(OUTF, "> $out_file");
#
print OUTF "\n";
print OUTF "Generated by:         score_scale.pl\n";
print OUTF "Gold Standard File:   $gold_file\n";
print OUTF "Test File:            $test_file\n";
print OUTF "Number of Pairs:      $num_gold\n";
print OUTF "Spearman Correlation: $rho\n";
print OUTF "\n";
#
close(OUTF);
#
print "... done.\n";
#
#
#
#
#
#